backend:
  name: git-gateway

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: "Slider", name: slider, widget: list, fields: [
              {label: "Image", name: "image", widget: image}]}
          - {label: "first_box", name: first_box, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "second_box", name: second_box, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "ServiceLead", name: service_lead, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "SubHeading", name: "subheading", widget: string}]}
          - {label: "Services", name: services, widget: list, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Color", name: "color", widget: text},
              {label: "icon", name: "icon", widget: text},
              {label: "Text", name: "text", widget: text}]}
          - {label: "SpotlightLead", name: spotlight_lead, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "SubHeading", name: "subheading", widget: string}]}
          - {label: "Spotlights", name: spotlights, widget: list, fields: [
              {label: "Image", name: "image", widget: image},
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: text}]}
          - {label: "Footer", name: footer, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: text}]}
          - {label: "ContactList", name: contact_list, widget: list, fields: [
              {label: "Icon", name: "icon", widget: string},
              {label: "Link", name: "link", widget: string},
              {label: "Text", name: "text", widget: text}]}
